import type { Agent } from "@/types/agent";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1on1",
    name: "1-on-1 Prep Report",
    description: "Generate manager prep briefs for upcoming 1-on-1s with data-driven insights",
    icon: "user-check",
    category: "People Management",
    purpose: "People Manager",
    tags: ["1-on-1", "Coaching", "Benchmarks"],
    integrations: ["outlook", "slack"],
    is_favorite: true,
    usage_count: 142,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    last_generated: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "agent-workload",
    name: "Workload Analyzer",
    description: "Analyze team capacity and burnout risks across your direct reports",
    icon: "bar-chart-3",
    category: "Productivity & Efficiency",
    purpose: "Team Lead",
    tags: ["Workload", "Burnout", "Capacity"],
    integrations: ["outlook", "teams"],
    is_favorite: false,
    usage_count: 98,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    last_generated: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "agent-sentiment",
    name: "Team Sentiment",
    description: "Surface engagement and morale signals from team communication data",
    icon: "heart-pulse",
    category: "People Management",
    purpose: "People Manager",
    tags: ["Engagement", "Wellness", "Morale"],
    integrations: ["slack", "teams"],
    is_favorite: true,
    usage_count: 67,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    last_generated: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "agent-review",
    name: "Review Writer",
    description: "Draft performance review summaries with evidence-based insights",
    icon: "file-text",
    category: "People Management",
    purpose: "People Manager",
    tags: ["Performance", "Reviews", "Feedback"],
    integrations: ["outlook", "gmail"],
    is_favorite: false,
    usage_count: 55,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    last_generated: null,
  },
  {
    id: "agent-strategy",
    name: "Strategy Alignment Report",
    description: "Measure alignment between leadership goals and team execution",
    icon: "target",
    category: "Leadership & Strategy",
    purpose: "Senior Leader",
    tags: ["Alignment", "Strategy", "OKRs"],
    integrations: ["outlook", "slack", "teams"],
    is_favorite: true,
    usage_count: 89,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    last_generated: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "agent-meeting-cost",
    name: "Meeting Cost Optimizer",
    description: "Identify high-cost meetings and recommend efficiency improvements",
    icon: "calculator",
    category: "Productivity & Efficiency",
    purpose: "Operations",
    tags: ["Meetings", "Cost", "Efficiency"],
    integrations: ["outlook"],
    is_favorite: false,
    usage_count: 73,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    last_generated: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "agent-onboarding",
    name: "New Hire Onboarding Tracker",
    description: "Monitor onboarding progress and flag at-risk new hires early",
    icon: "user-plus",
    category: "People Management",
    purpose: "HR Partner",
    tags: ["Onboarding", "New Hires", "Retention"],
    integrations: ["slack", "teams", "outlook"],
    is_favorite: false,
    usage_count: 34,
    last_used: null,
    last_generated: null,
  },
  {
    id: "agent-decision",
    name: "Decision Quality Analyzer",
    description: "Evaluate meeting decision quality and track follow-through rates",
    icon: "git-branch",
    category: "Leadership & Strategy",
    purpose: "Senior Leader",
    tags: ["Decisions", "Accountability", "Follow-up"],
    integrations: ["outlook", "slack"],
    is_favorite: false,
    usage_count: 41,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    last_generated: null,
  },
  {
    id: "agent-focus",
    name: "Deep Work Protector",
    description: "Protect focus time by analyzing meeting fragmentation patterns",
    icon: "shield",
    category: "Productivity & Efficiency",
    purpose: "Team Lead",
    tags: ["Focus Time", "Deep Work", "Interruptions"],
    integrations: ["outlook", "teams"],
    is_favorite: true,
    usage_count: 112,
    last_used: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    last_generated: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "agent-compliance",
    name: "Compliance Monitor",
    description: "Track external meeting compliance and flag NDA or policy gaps",
    icon: "shield-check",
    category: "Leadership & Strategy",
    purpose: "Compliance Officer",
    tags: ["Compliance", "NDA", "Policy"],
    integrations: ["outlook", "gmail"],
    is_favorite: false,
    usage_count: 28,
    last_used: null,
    last_generated: null,
  },
];
