import type { LearningModule } from "@/types/learning";

export const MODULE_ICONS: Record<string, string> = {
  "module-system": "Server",
  "module-api": "Plug",
  "module-data": "Database",
  "module-error": "Bug",
  "module-deploy": "Rocket",
};

export const MOCK_LEARNING_MODULES: LearningModule[] = [
  {
    id: "module-system",
    title: "System & Architecture",
    description: "Understand how modern web systems are structured and communicate",
    icon: "server",
    sort_order: 1,
    progress_percent: 0,
    topics: [
      { id: "topic-frontend-backend-db", title: "Frontend, Backend & Database", description: "The three layers of every web application", learning_objective: "Explain the roles of frontend, backend, and database", sort_order: 1, estimated_minutes: 5, completed: false },
      { id: "topic-client-server", title: "Client-Server Model", description: "How your browser talks to a server", learning_objective: "Describe the request-response cycle", sort_order: 2, estimated_minutes: 4, completed: false },
      { id: "topic-monolith-microservice", title: "Monolith vs Microservice", description: "How systems are organised and what it means for your work", learning_objective: "Compare monolith and microservice architectures", sort_order: 3, estimated_minutes: 6, completed: false },
      { id: "topic-api-gateway", title: "API Gateway", description: "The front door of a system", learning_objective: "Explain what an API Gateway does", sort_order: 4, estimated_minutes: 4, completed: false },
      { id: "topic-sync-async", title: "Sync vs Async Communication", description: "When to wait and when to move on", learning_objective: "Distinguish synchronous and asynchronous flows", sort_order: 5, estimated_minutes: 5, completed: false },
      { id: "topic-queue-broker", title: "Queue & Message Broker", description: "How systems talk without blocking each other", learning_objective: "Explain message queues with a business example", sort_order: 6, estimated_minutes: 5, completed: false },
    ],
  },
  {
    id: "module-api",
    title: "API",
    description: "Learn the language of APIs and integrations",
    icon: "plug",
    sort_order: 2,
    progress_percent: 0,
    topics: [
      { id: "topic-rest-api", title: "REST API", description: "The most common way systems communicate", learning_objective: "Explain what a REST API is", sort_order: 1, estimated_minutes: 5, completed: false },
      { id: "topic-endpoint-method", title: "Endpoint & Method", description: "How to read and understand API endpoints", learning_objective: "Identify HTTP methods and their purposes", sort_order: 2, estimated_minutes: 4, completed: false },
      { id: "topic-header-body-param", title: "Header, Body & Parameter", description: "The three places information travels in a request", learning_objective: "Distinguish headers, body, and parameters", sort_order: 3, estimated_minutes: 5, completed: false },
      { id: "topic-json-structure", title: "JSON Structure", description: "What BAs need to read when reviewing API responses", learning_objective: "Read a JSON response and identify key fields", sort_order: 4, estimated_minutes: 5, completed: false },
      { id: "topic-webhook-polling", title: "Webhook vs Polling", description: "Push vs pull — two ways to get updates", learning_objective: "Compare webhooks and polling", sort_order: 5, estimated_minutes: 4, completed: false },
      { id: "topic-auth-authz", title: "Authentication vs Authorization", description: "Who you are vs what you can do", learning_objective: "Distinguish authentication and authorization", sort_order: 6, estimated_minutes: 4, completed: false },
      { id: "topic-token-jwt", title: "Token & JWT", description: "How systems remember who you are between requests", learning_objective: "Explain JWT tokens", sort_order: 7, estimated_minutes: 5, completed: false },
    ],
  },
  {
    id: "module-data",
    title: "Data & Database Thinking",
    description: "Think about data the way engineers do",
    icon: "database",
    sort_order: 3,
    progress_percent: 0,
    topics: [
      { id: "topic-table-field-record", title: "Table, Field & Record", description: "The building blocks of structured data", learning_objective: "Map a business concept to a table structure", sort_order: 1, estimated_minutes: 4, completed: false },
      { id: "topic-pk-fk", title: "Primary Key vs Foreign Key", description: "How records link to each other", learning_objective: "Explain primary and foreign keys", sort_order: 2, estimated_minutes: 4, completed: false },
      { id: "topic-enum-status", title: "Enum & Status", description: "Controlling what values are allowed", learning_objective: "Define an enum for a status field", sort_order: 3, estimated_minutes: 3, completed: false },
      { id: "topic-soft-hard-delete", title: "Soft Delete vs Hard Delete", description: "Why deleted data often isn't really gone", learning_objective: "Compare soft and hard delete", sort_order: 4, estimated_minutes: 4, completed: false },
      { id: "topic-data-mapping", title: "Data Mapping", description: "How data translates when moving between systems", learning_objective: "Write a data mapping spec", sort_order: 5, estimated_minutes: 5, completed: false },
      { id: "topic-data-validation", title: "Data Validation Layer", description: "Catching bad data before it causes problems", learning_objective: "Describe validation layers", sort_order: 6, estimated_minutes: 4, completed: false },
    ],
  },
  {
    id: "module-error",
    title: "Error & Debug Mindset",
    description: "Build your debugging intuition and error literacy",
    icon: "bug",
    sort_order: 4,
    progress_percent: 0,
    topics: [
      { id: "topic-status-codes", title: "HTTP Status Codes", description: "The traffic signals of the web", learning_objective: "Identify common status codes", sort_order: 1, estimated_minutes: 4, completed: false },
      { id: "topic-logs", title: "Logs", description: "The system diary that records everything that happens", learning_objective: "Explain logs and log levels", sort_order: 2, estimated_minutes: 4, completed: false },
      { id: "topic-trace-id", title: "Trace ID", description: "Tracking a single request across the entire system", learning_objective: "Explain how Trace IDs speed up debugging", sort_order: 3, estimated_minutes: 3, completed: false },
      { id: "topic-timeout", title: "Timeout", description: "When the system has waited too long and gives up", learning_objective: "Explain timeout and its business risk", sort_order: 4, estimated_minutes: 4, completed: false },
      { id: "topic-retry-logic", title: "Retry Logic", description: "Automatically trying again — and when it's dangerous", learning_objective: "Explain retry and idempotency risk", sort_order: 5, estimated_minutes: 4, completed: false },
      { id: "topic-cache", title: "Cache", description: "Why you changed it but can't see the change", learning_objective: "Explain caching and stale data", sort_order: 6, estimated_minutes: 5, completed: false },
    ],
  },
  {
    id: "module-deploy",
    title: "Deployment & Environment",
    description: "Understand how code gets from laptop to production",
    icon: "rocket",
    sort_order: 5,
    progress_percent: 0,
    topics: [
      { id: "topic-dev-uat-prod", title: "Dev / UAT / Staging / Production", description: "The journey of code through environments", learning_objective: "Name the standard environments and their purposes", sort_order: 1, estimated_minutes: 5, completed: false },
      { id: "topic-build-deploy", title: "Build vs Deploy", description: "Compiling code vs releasing it", learning_objective: "Distinguish building and deploying", sort_order: 2, estimated_minutes: 4, completed: false },
      { id: "topic-versioning", title: "Versioning", description: "How software tracks changes across releases", learning_objective: "Explain semantic versioning", sort_order: 3, estimated_minutes: 4, completed: false },
      { id: "topic-feature-flag", title: "Feature Flag", description: "Turning features on and off without deploying", learning_objective: "Explain feature flags and safe rollouts", sort_order: 4, estimated_minutes: 4, completed: false },
      { id: "topic-rollback", title: "Rollback", description: "When things go wrong, go back", learning_objective: "Describe rollback strategies", sort_order: 5, estimated_minutes: 4, completed: false },
    ],
  },
];
