import type { Agent, AgentCategory } from "@/types/agent";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1on1",
    name: "1-on-1 Prep Brief",
    description: "Generate manager prep briefs for upcoming 1-on-1s",
    icon: "user-check",
    category: "People Management" as AgentCategory,
    purpose: "People Manager",
    tags: ["1-on-1", "Coaching", "Benchmarks", "Investigation"],
    integrations: ["outlook", "teams", "google-calendar"],
    is_favorite: true,
    usage_count: 142,
    last_used: new Date().toISOString(),
    last_generated: new Date().toISOString(),
  },
  {
    id: "agent-executive",
    name: "Executive Digest Agent",
    description:
      "Generate executive-level dashboards and signal reports for company-wide or department-level meeting analytics",
    icon: "bar-chart-3",
    category: "Leadership & Strategy" as AgentCategory,
    purpose: "Senior Leader",
    tags: ["Board-Ready", "Talent", "Capacity", "Risk"],
    integrations: ["outlook", "google-calendar"],
    is_favorite: true,
    usage_count: 98,
    last_used: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_generated: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "agent-recurring",
    name: "Recurring Meeting Audit",
    description:
      "Review all recurring meetings for cost, quality, and attendance with actionable recommendations",
    icon: "repeat",
    category: "Productivity & Efficiency" as AgentCategory,
    purpose: "Team Lead",
    tags: ["Cost", "Quality", "Attendance", "Audit"],
    integrations: ["outlook", "teams", "slack"],
    is_favorite: false,
    usage_count: 67,
    last_used: new Date(Date.now() - 5 * 86400000).toISOString(),
    last_generated: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "agent-team-health",
    name: "Team Health Check",
    description:
      "Measure team health related to meeting patterns with engagement, workload, and collaboration insights",
    icon: "heart-pulse",
    category: "People Management" as AgentCategory,
    purpose: "People Manager",
    tags: ["Wellness", "Engagement", "Workload", "Monitor"],
    integrations: ["outlook", "teams", "google-calendar", "slack"],
    is_favorite: false,
    usage_count: 55,
    last_used: new Date(Date.now() - 10 * 86400000).toISOString(),
    last_generated: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];
