import type { Agent, AgentCategory } from "@/types/agent";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1on1",
    name: "1-on-1 Prep Report",
    description: "Generate manager prep briefs for upcoming 1-on-1s",
    icon: "user-check",
    category: "People Management" as AgentCategory,
    purpose: "People Manager",
    tags: ["1-on-1", "Coaching", "Benchmarks"],
    integrations: ["outlook", "teams", "google-calendar"],
    is_favorite: true,
    usage_count: 142,
    last_used: new Date().toISOString(),
    last_generated: new Date().toISOString(),
  },
  {
    id: "agent-workload",
    name: "Workload Analyzer",
    description: "Analyze team capacity and burnout risks",
    icon: "bar-chart-3",
    category: "Productivity & Efficiency" as AgentCategory,
    purpose: "Team Lead",
    tags: ["Capacity", "Burnout", "Workload"],
    integrations: ["outlook", "slack"],
    is_favorite: false,
    usage_count: 98,
    last_used: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_generated: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "agent-sentiment",
    name: "Team Sentiment",
    description: "Surface engagement and morale signals from team data",
    icon: "heart-pulse",
    category: "Leadership & Strategy" as AgentCategory,
    purpose: "People Manager",
    tags: ["Engagement", "Morale", "Investigation"],
    integrations: ["teams", "slack"],
    is_favorite: true,
    usage_count: 67,
    last_used: new Date(Date.now() - 5 * 86400000).toISOString(),
    last_generated: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "agent-review",
    name: "Review Writer",
    description: "Draft performance review summaries",
    icon: "file-text",
    category: "People Management" as AgentCategory,
    purpose: "People Manager",
    tags: ["Performance", "Reviews", "Onboarding"],
    integrations: ["outlook", "google-calendar"],
    is_favorite: false,
    usage_count: 55,
    last_used: new Date(Date.now() - 10 * 86400000).toISOString(),
    last_generated: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];
